/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonApp } from './addonApp';

export class AddonInfoAttachment {
    'id': string;
    /**
    * Attachment name (e.g., DATABASE)
    */
    'name': string;
    'app': AddonApp;
    'state': AddonInfoAttachment.StateEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "AddonApp"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AddonInfoAttachment.StateEnum"
        }    ];

    static getAttributeTypeMap() {
        return AddonInfoAttachment.attributeTypeMap;
    }
}

export namespace AddonInfoAttachment {
    export enum StateEnum {
        Pending = <any> 'pending',
        Attached = <any> 'attached',
        Detached = <any> 'detached'
    }
}
