/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonServiceCategory } from './addonServiceCategory';

export class AddonServiceCatalogItem {
    'id': string;
    'name': string;
    'humanName': string;
    'state': string;
    'supportsLogDrains'?: boolean;
    'supportsSharing'?: boolean;
    'supportsMultipleInstallations'?: boolean;
    'category'?: AddonServiceCategory;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "humanName",
            "baseName": "human_name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "supportsLogDrains",
            "baseName": "supports_log_drains",
            "type": "boolean"
        },
        {
            "name": "supportsSharing",
            "baseName": "supports_sharing",
            "type": "boolean"
        },
        {
            "name": "supportsMultipleInstallations",
            "baseName": "supports_multiple_installations",
            "type": "boolean"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "AddonServiceCategory"
        }    ];

    static getAttributeTypeMap() {
        return AddonServiceCatalogItem.attributeTypeMap;
    }
}

