/**
 * Build.io API V1
 * ## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user\'s apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonApp } from './addonApp';
import { AddonBilledPrice } from './addonBilledPrice';
import { AddonPlan } from './addonPlan';
import { AddonService } from './addonService';

export class Addon {
    'id': string;
    /**
    * Globally unique addon name
    */
    'name'?: string | null;
    /**
    * User-provided display name for the addon
    */
    'humanName'?: string | null;
    /**
    * User-provided description of the addon
    */
    'description'?: string | null;
    'addonService': AddonService;
    'plan': AddonPlan;
    'app': AddonApp;
    'state': Addon.StateEnum;
    /**
    * Config var names provided by this addon
    */
    'configVars'?: Array<string>;
    'billedPrice'?: AddonBilledPrice;
    'webUrl'?: string | null;
    'createdAt'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "humanName",
            "baseName": "human_name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "addonService",
            "baseName": "addon_service",
            "type": "AddonService"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "AddonPlan"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "AddonApp"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Addon.StateEnum"
        },
        {
            "name": "configVars",
            "baseName": "config_vars",
            "type": "Array<string>"
        },
        {
            "name": "billedPrice",
            "baseName": "billed_price",
            "type": "AddonBilledPrice"
        },
        {
            "name": "webUrl",
            "baseName": "web_url",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Addon.attributeTypeMap;
    }
}

export namespace Addon {
    export enum StateEnum {
        Pending = <any> 'pending',
        Requested = <any> 'requested',
        Provisioned = <any> 'provisioned',
        Deprovisioning = <any> 'deprovisioning',
        Deprovisioned = <any> 'deprovisioned'
    }
}
