/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonApp } from './addonApp';
import { AttachmentAddon } from './attachmentAddon';

export class AddonAttachment {
    'id': string;
    /**
    * Attachment name (e.g., DATABASE, DATABASE_RED)
    */
    'name': string;
    'addon': AttachmentAddon;
    'app': AddonApp;
    'state': AddonAttachment.StateEnum;
    'createdAt'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "addon",
            "baseName": "addon",
            "type": "AttachmentAddon"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "AddonApp"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AddonAttachment.StateEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AddonAttachment.attributeTypeMap;
    }
}

export namespace AddonAttachment {
    export enum StateEnum {
        Pending = <any> 'pending',
        Attached = <any> 'attached',
        Detached = <any> 'detached'
    }
}
