/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonApp } from './addonApp';
import { AddonBilledPrice } from './addonBilledPrice';
import { AddonInfoAttachment } from './addonInfoAttachment';
import { AddonPlan } from './addonPlan';
import { AddonService } from './addonService';

export class AddonWithAttachments {
    'id': string;
    /**
    * Globally unique addon name
    */
    'name'?: string | null;
    /**
    * User-provided description of the addon
    */
    'description'?: string | null;
    'addonService': AddonService;
    'plan': AddonPlan;
    'app': AddonApp;
    'state': AddonWithAttachments.StateEnum;
    'configVars'?: Array<string>;
    'billedPrice'?: AddonBilledPrice;
    'webUrl'?: string | null;
    'attachments'?: Array<AddonInfoAttachment>;
    'createdAt'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "addonService",
            "baseName": "addon_service",
            "type": "AddonService"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "AddonPlan"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "AddonApp"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AddonWithAttachments.StateEnum"
        },
        {
            "name": "configVars",
            "baseName": "config_vars",
            "type": "Array<string>"
        },
        {
            "name": "billedPrice",
            "baseName": "billed_price",
            "type": "AddonBilledPrice"
        },
        {
            "name": "webUrl",
            "baseName": "web_url",
            "type": "string"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<AddonInfoAttachment>"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AddonWithAttachments.attributeTypeMap;
    }
}

export namespace AddonWithAttachments {
    export enum StateEnum {
        Pending = <any> 'pending',
        Requested = <any> 'requested',
        Provisioned = <any> 'provisioned',
        Deprovisioning = <any> 'deprovisioning',
        Deprovisioned = <any> 'deprovisioned'
    }
}
