/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddonPlanPrice } from './addonPlanPrice';

export class AddonPlanCatalogItem {
    'id': string;
    'name': string;
    'humanName': string;
    'description'?: string | null;
    'state': string;
    'isVisible'?: boolean;
    'monthlyPrice'?: AddonPlanPrice;
    'yearlyPrice'?: AddonPlanPrice;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "humanName",
            "baseName": "human_name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "isVisible",
            "baseName": "is_visible",
            "type": "boolean"
        },
        {
            "name": "monthlyPrice",
            "baseName": "monthly_price",
            "type": "AddonPlanPrice"
        },
        {
            "name": "yearlyPrice",
            "baseName": "yearly_price",
            "type": "AddonPlanPrice"
        }    ];

    static getAttributeTypeMap() {
        return AddonPlanCatalogItem.attributeTypeMap;
    }
}

