/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppBuildpack } from './appBuildpack';
import { AppFormationValue } from './appFormationValue';
import { AppPipeline } from './appPipeline';
import { AppTeam } from './appTeam';

export class App {
    'id': string;
    'name': string;
    'team': AppTeam;
    'pipeline'?: AppPipeline | null;
    'dnsRefreshedAt'?: string | null;
    'buildsCount'?: number;
    'deploymentsCount'?: number;
    'slugsCount'?: number;
    'currentBuildId'?: string | null;
    'currentImageId'?: string | null;
    'currentDeploymentId'?: string | null;
    'formation'?: { [key: string]: AppFormationValue; };
    'stack': string;
    'region': string;
    'buildpacks'?: Array<AppBuildpack>;
    'description'?: string | null;
    'pipelineStage'?: string | null;
    'policyAllowWebsockets'?: boolean;
    'policyResponseTimeout'?: number;
    'policyMaxConnections'?: number;
    'policyErosionResistanceSeconds'?: number;
    'policyShareProcessNamespace'?: boolean;
    'policyTemporarySelfSigned'?: boolean;
    'createdAt'?: string;
    'updatedAt'?: string;
    'deletedAt'?: string | null;
    'branch'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "AppTeam"
        },
        {
            "name": "pipeline",
            "baseName": "pipeline",
            "type": "AppPipeline"
        },
        {
            "name": "dnsRefreshedAt",
            "baseName": "dns_refreshed_at",
            "type": "string"
        },
        {
            "name": "buildsCount",
            "baseName": "builds_count",
            "type": "number"
        },
        {
            "name": "deploymentsCount",
            "baseName": "deployments_count",
            "type": "number"
        },
        {
            "name": "slugsCount",
            "baseName": "slugs_count",
            "type": "number"
        },
        {
            "name": "currentBuildId",
            "baseName": "current_build_id",
            "type": "string"
        },
        {
            "name": "currentImageId",
            "baseName": "current_image_id",
            "type": "string"
        },
        {
            "name": "currentDeploymentId",
            "baseName": "current_deployment_id",
            "type": "string"
        },
        {
            "name": "formation",
            "baseName": "formation",
            "type": "{ [key: string]: AppFormationValue; }"
        },
        {
            "name": "stack",
            "baseName": "stack",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "buildpacks",
            "baseName": "buildpacks",
            "type": "Array<AppBuildpack>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "pipelineStage",
            "baseName": "pipeline_stage",
            "type": "string"
        },
        {
            "name": "policyAllowWebsockets",
            "baseName": "policy_allow_websockets",
            "type": "boolean"
        },
        {
            "name": "policyResponseTimeout",
            "baseName": "policy_response_timeout",
            "type": "number"
        },
        {
            "name": "policyMaxConnections",
            "baseName": "policy_max_connections",
            "type": "number"
        },
        {
            "name": "policyErosionResistanceSeconds",
            "baseName": "policy_erosion_resistance_seconds",
            "type": "number"
        },
        {
            "name": "policyShareProcessNamespace",
            "baseName": "policy_share_process_namespace",
            "type": "boolean"
        },
        {
            "name": "policyTemporarySelfSigned",
            "baseName": "policy_temporary_self_signed",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "string"
        },
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return App.attributeTypeMap;
    }
}

