/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BuildpackInstallationBuildpack } from './buildpackInstallationBuildpack';

export class BuildpackInstallation {
    /**
    * Determines the order in which the buildpacks will execute
    */
    'ordinal': number;
    'buildpack': BuildpackInstallationBuildpack;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "buildpack",
            "baseName": "buildpack",
            "type": "BuildpackInstallationBuildpack"
        }    ];

    static getAttributeTypeMap() {
        return BuildpackInstallation.attributeTypeMap;
    }
}

