/**
 * Build.io API V1
 * ## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user\'s apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BuildBuildpacksInner } from './buildBuildpacksInner';
import { BuildSlug } from './buildSlug';
import { BuildSourceBlob } from './buildSourceBlob';
import { BuildUser } from './buildUser';
import { GetPipelineDiff200ResponseSource } from './getPipelineDiff200ResponseSource';

export class Build {
    'id': string;
    'app': GetPipelineDiff200ResponseSource;
    'user'?: BuildUser;
    'sourceBlob'?: BuildSourceBlob;
    'buildpacks'?: Array<BuildBuildpacksInner> | null;
    'stack': string | null;
    /**
    * Build state, reported verbatim rather than collapsed.
    */
    'state': Build.StateEnum;
    'outputStreamUrl'?: string | null;
    'slug'?: BuildSlug | null;
    'createdAt': Date;
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "GetPipelineDiff200ResponseSource"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "BuildUser"
        },
        {
            "name": "sourceBlob",
            "baseName": "source_blob",
            "type": "BuildSourceBlob"
        },
        {
            "name": "buildpacks",
            "baseName": "buildpacks",
            "type": "Array<BuildBuildpacksInner>"
        },
        {
            "name": "stack",
            "baseName": "stack",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Build.StateEnum"
        },
        {
            "name": "outputStreamUrl",
            "baseName": "output_stream_url",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "BuildSlug"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Build.attributeTypeMap;
    }
}

export namespace Build {
    export enum StateEnum {
        Pending = <any> 'pending',
        Packing = <any> 'packing',
        Uploading = <any> 'uploading',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
