/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollaboratorApp } from './collaboratorApp';
import { CollaboratorUser } from './collaboratorUser';

export class Collaborator {
    'id': string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'user': CollaboratorUser;
    'app': CollaboratorApp;
    'role': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "CollaboratorUser"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "CollaboratorApp"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Collaborator.attributeTypeMap;
    }
}

