/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateAddonRequest {
    /**
    * Addon service and plan in format \"service:plan\"
    */
    'plan': string;
    /**
    * Globally unique addon name (optional)
    */
    'name'?: string | null;
    /**
    * User-provided display name for the addon (optional)
    */
    'humanName'?: string | null;
    /**
    * User-provided description of the addon (optional)
    */
    'description'?: string | null;
    /**
    * Addon-specific configuration options (use list-addon-fields to discover available options for each service)
    */
    'config'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "humanName",
            "baseName": "human_name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return CreateAddonRequest.attributeTypeMap;
    }
}

