/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateReviewAppRequest {
    /**
    * Branch to build the review app from
    */
    'branch': string;
    /**
    * Pull request number
    */
    'pullRequestNumber': number;
    /**
    * URL to the source code archive
    */
    'sourceBlobUrl'?: string | null;
    /**
    * Title of the pull request
    */
    'title'?: string | null;
    /**
    * Description of the pull request
    */
    'description'?: string | null;
    /**
    * GitHub repository stub (owner/repo)
    */
    'githubRepo'?: string | null;
    /**
    * Environment variables for the app
    */
    'environment'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string"
        },
        {
            "name": "pullRequestNumber",
            "baseName": "pull_request_number",
            "type": "number"
        },
        {
            "name": "sourceBlobUrl",
            "baseName": "source_blob_url",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "githubRepo",
            "baseName": "github_repo",
            "type": "string"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return CreateReviewAppRequest.attributeTypeMap;
    }
}

