/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreatePipelinePromotionRequestSource } from './createPipelinePromotionRequestSource';
import { CreatePipelinePromotionRequestTargetsInner } from './createPipelinePromotionRequestTargetsInner';

export class CreatePipelinePromotionRequest {
    'source': CreatePipelinePromotionRequestSource;
    /**
    * Target apps. Omit to promote to all downstream apps.
    */
    'targets'?: Array<CreatePipelinePromotionRequestTargetsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "CreatePipelinePromotionRequestSource"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<CreatePipelinePromotionRequestTargetsInner>"
        }    ];

    static getAttributeTypeMap() {
        return CreatePipelinePromotionRequest.attributeTypeMap;
    }
}

