/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateAddonAttachmentRequest {
    /**
    * Addon name or ID to attach
    */
    'addon': string;
    /**
    * App name or ID to attach the addon to
    */
    'app': string;
    /**
    * Attachment name (e.g., DATABASE_RED)
    */
    'name'?: string | null;
    /**
    * Owning app name for confirmation
    */
    'confirm'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addon",
            "baseName": "addon",
            "type": "string"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "confirm",
            "baseName": "confirm",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateAddonAttachmentRequest.attributeTypeMap;
    }
}

