/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DomainApp } from './domainApp';
import { DomainSniEndpoint } from './domainSniEndpoint';

export class Domain {
    'id': string;
    /**
    * The domain name
    */
    'hostname': string;
    /**
    * Type of domain
    */
    'kind': Domain.KindEnum;
    /**
    * CNAME target for DNS configuration
    */
    'cname'?: string | null;
    /**
    * Domain status
    */
    'status': Domain.StatusEnum;
    /**
    * SSL certificate status
    */
    'acmStatus'?: string | null;
    /**
    * Reason for certificate status
    */
    'acmStatusReason'?: string | null;
    'createdAt'?: string;
    'updatedAt'?: string;
    'sniEndpoint'?: DomainSniEndpoint | null;
    'app': DomainApp;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "Domain.KindEnum"
        },
        {
            "name": "cname",
            "baseName": "cname",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Domain.StatusEnum"
        },
        {
            "name": "acmStatus",
            "baseName": "acm_status",
            "type": "string"
        },
        {
            "name": "acmStatusReason",
            "baseName": "acm_status_reason",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "sniEndpoint",
            "baseName": "sni_endpoint",
            "type": "DomainSniEndpoint"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "DomainApp"
        }    ];

    static getAttributeTypeMap() {
        return Domain.attributeTypeMap;
    }
}

export namespace Domain {
    export enum KindEnum {
        Platform = <any> 'platform',
        Custom = <any> 'custom'
    }
    export enum StatusEnum {
        Pending = <any> 'pending',
        Deployed = <any> 'deployed',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
