/**
 * Build.io API V1
 * ## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user\'s apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DynoRunRequest {
    /**
    * Shell command to run
    */
    'command': string;
    /**
    * Process type (default: worker)
    */
    'type'?: string;
    /**
    * Dyno size (default: from formation)
    */
    'size'?: string;
    /**
    * Timeout in seconds (30–1800, default: 300)
    */
    'timeout'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DynoRunRequest.attributeTypeMap;
    }
}

