/**
 * Build.io API V1
 * ## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user\'s apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetPipelineDiff200ResponseDiffsInnerCommitsInner } from './getPipelineDiff200ResponseDiffsInnerCommitsInner';
import { GetPipelineDiff200ResponseSource } from './getPipelineDiff200ResponseSource';

export class GetPipelineDiff200ResponseDiffsInner {
    'app'?: GetPipelineDiff200ResponseSource;
    'status'?: GetPipelineDiff200ResponseDiffsInner.StatusEnum;
    'aheadBy'?: number;
    'behindBy'?: number;
    'errorMessage'?: string;
    'commits'?: Array<GetPipelineDiff200ResponseDiffsInnerCommitsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "GetPipelineDiff200ResponseSource"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GetPipelineDiff200ResponseDiffsInner.StatusEnum"
        },
        {
            "name": "aheadBy",
            "baseName": "ahead_by",
            "type": "number"
        },
        {
            "name": "behindBy",
            "baseName": "behind_by",
            "type": "number"
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string"
        },
        {
            "name": "commits",
            "baseName": "commits",
            "type": "Array<GetPipelineDiff200ResponseDiffsInnerCommitsInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetPipelineDiff200ResponseDiffsInner.attributeTypeMap;
    }
}

export namespace GetPipelineDiff200ResponseDiffsInner {
    export enum StatusEnum {
        Ahead = <any> 'ahead',
        Behind = <any> 'behind',
        Identical = <any> 'identical',
        Diverged = <any> 'diverged',
        Error = <any> 'error',
        Unavailable = <any> 'unavailable'
    }
}
