/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetPipelineDiff200ResponseDiffsInnerCommitsInner } from './getPipelineDiff200ResponseDiffsInnerCommitsInner';
import { GetPipelineDiff200ResponseSource } from './getPipelineDiff200ResponseSource';

export class GetPipelineDiff200ResponseDiffsInner {
    'app'?: GetPipelineDiff200ResponseSource;
    'status'?: GetPipelineDiff200ResponseDiffsInner.StatusEnum;
    'aheadBy'?: number;
    'behindBy'?: number;
    'errorMessage'?: string;
    'commits'?: Array<GetPipelineDiff200ResponseDiffsInnerCommitsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "GetPipelineDiff200ResponseSource"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GetPipelineDiff200ResponseDiffsInner.StatusEnum"
        },
        {
            "name": "aheadBy",
            "baseName": "ahead_by",
            "type": "number"
        },
        {
            "name": "behindBy",
            "baseName": "behind_by",
            "type": "number"
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string"
        },
        {
            "name": "commits",
            "baseName": "commits",
            "type": "Array<GetPipelineDiff200ResponseDiffsInnerCommitsInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetPipelineDiff200ResponseDiffsInner.attributeTypeMap;
    }
}

export namespace GetPipelineDiff200ResponseDiffsInner {
    export enum StatusEnum {
        Ahead = <any> 'ahead',
        Behind = <any> 'behind',
        Identical = <any> 'identical',
        Diverged = <any> 'diverged',
        Error = <any> 'error',
        Unavailable = <any> 'unavailable'
    }
}
