/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetPipelineDiff200ResponseDiffsInner } from './getPipelineDiff200ResponseDiffsInner';
import { GetPipelineDiff200ResponseSource } from './getPipelineDiff200ResponseSource';

export class GetPipelineDiff200Response {
    'source'?: GetPipelineDiff200ResponseSource;
    'diffs'?: Array<GetPipelineDiff200ResponseDiffsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "GetPipelineDiff200ResponseSource"
        },
        {
            "name": "diffs",
            "baseName": "diffs",
            "type": "Array<GetPipelineDiff200ResponseDiffsInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetPipelineDiff200Response.attributeTypeMap;
    }
}

