/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OidcLoginResponseSpec } from './oidcLoginResponseSpec';
import { OidcLoginResponseStatus } from './oidcLoginResponseStatus';

export class OidcLoginResponse {
    'kind': string;
    'apiVersion': string;
    'spec': OidcLoginResponseSpec;
    'status': OidcLoginResponseStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "spec",
            "baseName": "spec",
            "type": "OidcLoginResponseSpec"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OidcLoginResponseStatus"
        }    ];

    static getAttributeTypeMap() {
        return OidcLoginResponse.attributeTypeMap;
    }
}

