/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromotionPipeline } from './promotionPipeline';
import { PromotionSource } from './promotionSource';

export class PipelinePromotion {
    'id': string;
    'status': PipelinePromotion.StatusEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
    'pipeline': PromotionPipeline;
    'source': PromotionSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PipelinePromotion.StatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "pipeline",
            "baseName": "pipeline",
            "type": "PromotionPipeline"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "PromotionSource"
        }    ];

    static getAttributeTypeMap() {
        return PipelinePromotion.attributeTypeMap;
    }
}

export namespace PipelinePromotion {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
