/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PipelineEnvironmentsInner {
    'id'?: string;
    'kind'?: PipelineEnvironmentsInner.KindEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "PipelineEnvironmentsInner.KindEnum"
        }    ];

    static getAttributeTypeMap() {
        return PipelineEnvironmentsInner.attributeTypeMap;
    }
}

export namespace PipelineEnvironmentsInner {
    export enum KindEnum {
        Ra = <any> 'ra',
        Ci = <any> 'ci',
        Ai = <any> 'ai'
    }
}
