/**
 * Build.io API V1
 * ## Authentication  All endpoints accept an OAuth Bearer token in the `Authorization` header.  Tokens come in three kinds, distinguished by their resource owner:  - **User tokens** (default) — full access to the user\'s apps, teams, pipelines, and namespaces. - **App-scoped tokens** (prefix `bldp_`) — bound to a single app. Can only access endpoints   that operate on that one app (e.g. `GET /api/v1/apps/:id`, builds, dynos, config vars).   Endpoints that operate on user-level collections (`/api/v1/apps`, `/api/v1/teams`,   `/api/v1/pipelines`, `/api/v1/namespaces`, `/api/v1/addon-attachments`, `/api/v1/addons`)   return **403 Forbidden** for these tokens. - **Addon partner tokens** (`addon:config` scope) — issued to addon vendors for partner   endpoints only.  The `/api/v1/me` response shape varies by token kind: user tokens return `{ email }`; app-scoped tokens return `{ app, email }` where `email` belongs to the user that minted the token.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromotionPipeline } from './promotionPipeline';
import { PromotionSource } from './promotionSource';

export class PipelinePromotion {
    'id': string;
    'status': PipelinePromotion.StatusEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
    'pipeline': PromotionPipeline;
    'source': PromotionSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PipelinePromotion.StatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "pipeline",
            "baseName": "pipeline",
            "type": "PromotionPipeline"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "PromotionSource"
        }    ];

    static getAttributeTypeMap() {
        return PipelinePromotion.attributeTypeMap;
    }
}

export namespace PipelinePromotion {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
