/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Process {
    'index': number;
    'status': string;
    'startedAt': string;
    'restarts'?: number | null;
    'restartedAt'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "string"
        },
        {
            "name": "restarts",
            "baseName": "restarts",
            "type": "number"
        },
        {
            "name": "restartedAt",
            "baseName": "restarted_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Process.attributeTypeMap;
    }
}

