/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromotionTargetApp } from './promotionTargetApp';
import { PromotionTargetPromotion } from './promotionTargetPromotion';

export class PromotionTarget {
    'id': string;
    'status': PromotionTarget.StatusEnum;
    'errorMessage'?: string | null;
    'app': PromotionTargetApp;
    'pipelinePromotion': PromotionTargetPromotion;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PromotionTarget.StatusEnum"
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "PromotionTargetApp"
        },
        {
            "name": "pipelinePromotion",
            "baseName": "pipeline_promotion",
            "type": "PromotionTargetPromotion"
        }    ];

    static getAttributeTypeMap() {
        return PromotionTarget.attributeTypeMap;
    }
}

export namespace PromotionTarget {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Promoting = <any> 'promoting',
        Succeeded = <any> 'succeeded',
        Failed = <any> 'failed'
    }
}
