/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateAppRequest {
    /**
    * Stack for the next build (e.g. heroku-22, heroku-24)
    */
    'buildStack'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buildStack",
            "baseName": "build_stack",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateAppRequest.attributeTypeMap;
    }
}

