/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateBuildpacksRequestUpdatesInner } from './updateBuildpacksRequestUpdatesInner';

export class UpdateBuildpacksRequest {
    /**
    * Ordered list of buildpacks. The order determines execution order.
    */
    'updates': Array<UpdateBuildpacksRequestUpdatesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "updates",
            "baseName": "updates",
            "type": "Array<UpdateBuildpacksRequestUpdatesInner>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateBuildpacksRequest.attributeTypeMap;
    }
}

