/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1OidcLoginGet200ResponseSpec model module.
 * @module model/ApiV1OidcLoginGet200ResponseSpec
 * @version v1
 */
class ApiV1OidcLoginGet200ResponseSpec {
    /**
     * Constructs a new <code>ApiV1OidcLoginGet200ResponseSpec</code>.
     * @alias module:model/ApiV1OidcLoginGet200ResponseSpec
     */
    constructor() { 
        
        ApiV1OidcLoginGet200ResponseSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1OidcLoginGet200ResponseSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1OidcLoginGet200ResponseSpec} obj Optional instance to populate.
     * @return {module:model/ApiV1OidcLoginGet200ResponseSpec} The populated <code>ApiV1OidcLoginGet200ResponseSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1OidcLoginGet200ResponseSpec();

            if (data.hasOwnProperty('interactive')) {
                obj['interactive'] = ApiClient.convertToType(data['interactive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1OidcLoginGet200ResponseSpec</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1OidcLoginGet200ResponseSpec</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} interactive
 */
ApiV1OidcLoginGet200ResponseSpec.prototype['interactive'] = undefined;






export default ApiV1OidcLoginGet200ResponseSpec;

