/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1OidcLoginGet200ResponseStatus model module.
 * @module model/ApiV1OidcLoginGet200ResponseStatus
 * @version v1
 */
class ApiV1OidcLoginGet200ResponseStatus {
    /**
     * Constructs a new <code>ApiV1OidcLoginGet200ResponseStatus</code>.
     * @alias module:model/ApiV1OidcLoginGet200ResponseStatus
     */
    constructor() { 
        
        ApiV1OidcLoginGet200ResponseStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1OidcLoginGet200ResponseStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1OidcLoginGet200ResponseStatus} obj Optional instance to populate.
     * @return {module:model/ApiV1OidcLoginGet200ResponseStatus} The populated <code>ApiV1OidcLoginGet200ResponseStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1OidcLoginGet200ResponseStatus();

            if (data.hasOwnProperty('expirationTimestamp')) {
                obj['expirationTimestamp'] = ApiClient.convertToType(data['expirationTimestamp'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1OidcLoginGet200ResponseStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1OidcLoginGet200ResponseStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['expirationTimestamp'] && !(typeof data['expirationTimestamp'] === 'string' || data['expirationTimestamp'] instanceof String)) {
            throw new Error("Expected the field `expirationTimestamp` to be a primitive type in the JSON string but got " + data['expirationTimestamp']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}



/**
 * @member {String} expirationTimestamp
 */
ApiV1OidcLoginGet200ResponseStatus.prototype['expirationTimestamp'] = undefined;

/**
 * @member {String} token
 */
ApiV1OidcLoginGet200ResponseStatus.prototype['token'] = undefined;






export default ApiV1OidcLoginGet200ResponseStatus;

