/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1AppsIdBuildsPostRequest model module.
 * @module model/ApiV1AppsIdBuildsPostRequest
 * @version v1
 */
class ApiV1AppsIdBuildsPostRequest {
    /**
     * Constructs a new <code>ApiV1AppsIdBuildsPostRequest</code>.
     * @alias module:model/ApiV1AppsIdBuildsPostRequest
     */
    constructor() { 
        
        ApiV1AppsIdBuildsPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1AppsIdBuildsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1AppsIdBuildsPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiV1AppsIdBuildsPostRequest} The populated <code>ApiV1AppsIdBuildsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1AppsIdBuildsPostRequest();

            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
            }
            if (data.hasOwnProperty('commitish')) {
                obj['commitish'] = ApiClient.convertToType(data['commitish'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1AppsIdBuildsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1AppsIdBuildsPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['branch'] && !(typeof data['branch'] === 'string' || data['branch'] instanceof String)) {
            throw new Error("Expected the field `branch` to be a primitive type in the JSON string but got " + data['branch']);
        }
        // ensure the json data is a string
        if (data['commitish'] && !(typeof data['commitish'] === 'string' || data['commitish'] instanceof String)) {
            throw new Error("Expected the field `commitish` to be a primitive type in the JSON string but got " + data['commitish']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} branch
 */
ApiV1AppsIdBuildsPostRequest.prototype['branch'] = undefined;

/**
 * @member {String} commitish
 */
ApiV1AppsIdBuildsPostRequest.prototype['commitish'] = undefined;

/**
 * @member {String} description
 */
ApiV1AppsIdBuildsPostRequest.prototype['description'] = undefined;






export default ApiV1AppsIdBuildsPostRequest;

