/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1OidcLoginGet200ResponseSpec from './ApiV1OidcLoginGet200ResponseSpec';
import ApiV1OidcLoginGet200ResponseStatus from './ApiV1OidcLoginGet200ResponseStatus';

/**
 * The ApiV1OidcLoginGet200Response model module.
 * @module model/ApiV1OidcLoginGet200Response
 * @version v1
 */
class ApiV1OidcLoginGet200Response {
    /**
     * Constructs a new <code>ApiV1OidcLoginGet200Response</code>.
     * @alias module:model/ApiV1OidcLoginGet200Response
     * @param kind {String} 
     * @param apiVersion {String} 
     * @param spec {module:model/ApiV1OidcLoginGet200ResponseSpec} 
     * @param status {module:model/ApiV1OidcLoginGet200ResponseStatus} 
     */
    constructor(kind, apiVersion, spec, status) { 
        
        ApiV1OidcLoginGet200Response.initialize(this, kind, apiVersion, spec, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind, apiVersion, spec, status) { 
        obj['kind'] = kind;
        obj['apiVersion'] = apiVersion;
        obj['spec'] = spec;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ApiV1OidcLoginGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1OidcLoginGet200Response} obj Optional instance to populate.
     * @return {module:model/ApiV1OidcLoginGet200Response} The populated <code>ApiV1OidcLoginGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1OidcLoginGet200Response();

            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('apiVersion')) {
                obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
            }
            if (data.hasOwnProperty('spec')) {
                obj['spec'] = ApiV1OidcLoginGet200ResponseSpec.constructFromObject(data['spec']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiV1OidcLoginGet200ResponseStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1OidcLoginGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1OidcLoginGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiV1OidcLoginGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }
        // ensure the json data is a string
        if (data['apiVersion'] && !(typeof data['apiVersion'] === 'string' || data['apiVersion'] instanceof String)) {
            throw new Error("Expected the field `apiVersion` to be a primitive type in the JSON string but got " + data['apiVersion']);
        }
        // validate the optional field `spec`
        if (data['spec']) { // data not null
          ApiV1OidcLoginGet200ResponseSpec.validateJSON(data['spec']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          ApiV1OidcLoginGet200ResponseStatus.validateJSON(data['status']);
        }

        return true;
    }


}

ApiV1OidcLoginGet200Response.RequiredProperties = ["kind", "apiVersion", "spec", "status"];

/**
 * @member {String} kind
 */
ApiV1OidcLoginGet200Response.prototype['kind'] = undefined;

/**
 * @member {String} apiVersion
 */
ApiV1OidcLoginGet200Response.prototype['apiVersion'] = undefined;

/**
 * @member {module:model/ApiV1OidcLoginGet200ResponseSpec} spec
 */
ApiV1OidcLoginGet200Response.prototype['spec'] = undefined;

/**
 * @member {module:model/ApiV1OidcLoginGet200ResponseStatus} status
 */
ApiV1OidcLoginGet200Response.prototype['status'] = undefined;






export default ApiV1OidcLoginGet200Response;

