/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppBuildpacksInner from './AppBuildpacksInner';
import AppFormationValue from './AppFormationValue';
import AppPipeline from './AppPipeline';
import AppTeam from './AppTeam';

/**
 * The App model module.
 * @module model/App
 * @version v1
 */
class App {
    /**
     * Constructs a new <code>App</code>.
     * @alias module:model/App
     * @param id {String} 
     * @param name {String} 
     * @param team {module:model/AppTeam} 
     * @param stack {String} 
     * @param region {String} 
     */
    constructor(id, name, team, stack, region) { 
        
        App.initialize(this, id, name, team, stack, region);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, team, stack, region) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['team'] = team;
        obj['stack'] = stack;
        obj['region'] = region;
    }

    /**
     * Constructs a <code>App</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/App} obj Optional instance to populate.
     * @return {module:model/App} The populated <code>App</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new App();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('team')) {
                obj['team'] = AppTeam.constructFromObject(data['team']);
            }
            if (data.hasOwnProperty('pipeline')) {
                obj['pipeline'] = AppPipeline.constructFromObject(data['pipeline']);
            }
            if (data.hasOwnProperty('dns_refreshed_at')) {
                obj['dns_refreshed_at'] = ApiClient.convertToType(data['dns_refreshed_at'], 'String');
            }
            if (data.hasOwnProperty('builds_count')) {
                obj['builds_count'] = ApiClient.convertToType(data['builds_count'], 'Number');
            }
            if (data.hasOwnProperty('deployments_count')) {
                obj['deployments_count'] = ApiClient.convertToType(data['deployments_count'], 'Number');
            }
            if (data.hasOwnProperty('slugs_count')) {
                obj['slugs_count'] = ApiClient.convertToType(data['slugs_count'], 'Number');
            }
            if (data.hasOwnProperty('current_build_id')) {
                obj['current_build_id'] = ApiClient.convertToType(data['current_build_id'], 'String');
            }
            if (data.hasOwnProperty('current_image_id')) {
                obj['current_image_id'] = ApiClient.convertToType(data['current_image_id'], 'String');
            }
            if (data.hasOwnProperty('current_deployment_id')) {
                obj['current_deployment_id'] = ApiClient.convertToType(data['current_deployment_id'], 'String');
            }
            if (data.hasOwnProperty('formation')) {
                obj['formation'] = ApiClient.convertToType(data['formation'], {'String': AppFormationValue});
            }
            if (data.hasOwnProperty('stack')) {
                obj['stack'] = ApiClient.convertToType(data['stack'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('buildpacks')) {
                obj['buildpacks'] = ApiClient.convertToType(data['buildpacks'], [AppBuildpacksInner]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('pipeline_stage')) {
                obj['pipeline_stage'] = ApiClient.convertToType(data['pipeline_stage'], 'String');
            }
            if (data.hasOwnProperty('policy_allow_websockets')) {
                obj['policy_allow_websockets'] = ApiClient.convertToType(data['policy_allow_websockets'], 'Boolean');
            }
            if (data.hasOwnProperty('policy_response_timeout')) {
                obj['policy_response_timeout'] = ApiClient.convertToType(data['policy_response_timeout'], 'Number');
            }
            if (data.hasOwnProperty('policy_max_connections')) {
                obj['policy_max_connections'] = ApiClient.convertToType(data['policy_max_connections'], 'Number');
            }
            if (data.hasOwnProperty('policy_erosion_resistance_seconds')) {
                obj['policy_erosion_resistance_seconds'] = ApiClient.convertToType(data['policy_erosion_resistance_seconds'], 'Number');
            }
            if (data.hasOwnProperty('policy_share_process_namespace')) {
                obj['policy_share_process_namespace'] = ApiClient.convertToType(data['policy_share_process_namespace'], 'Boolean');
            }
            if (data.hasOwnProperty('policy_temporary_self_signed')) {
                obj['policy_temporary_self_signed'] = ApiClient.convertToType(data['policy_temporary_self_signed'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>App</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>App</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of App.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `team`
        if (data['team']) { // data not null
          AppTeam.validateJSON(data['team']);
        }
        // validate the optional field `pipeline`
        if (data['pipeline']) { // data not null
          AppPipeline.validateJSON(data['pipeline']);
        }
        // ensure the json data is a string
        if (data['dns_refreshed_at'] && !(typeof data['dns_refreshed_at'] === 'string' || data['dns_refreshed_at'] instanceof String)) {
            throw new Error("Expected the field `dns_refreshed_at` to be a primitive type in the JSON string but got " + data['dns_refreshed_at']);
        }
        // ensure the json data is a string
        if (data['current_build_id'] && !(typeof data['current_build_id'] === 'string' || data['current_build_id'] instanceof String)) {
            throw new Error("Expected the field `current_build_id` to be a primitive type in the JSON string but got " + data['current_build_id']);
        }
        // ensure the json data is a string
        if (data['current_image_id'] && !(typeof data['current_image_id'] === 'string' || data['current_image_id'] instanceof String)) {
            throw new Error("Expected the field `current_image_id` to be a primitive type in the JSON string but got " + data['current_image_id']);
        }
        // ensure the json data is a string
        if (data['current_deployment_id'] && !(typeof data['current_deployment_id'] === 'string' || data['current_deployment_id'] instanceof String)) {
            throw new Error("Expected the field `current_deployment_id` to be a primitive type in the JSON string but got " + data['current_deployment_id']);
        }
        // ensure the json data is a string
        if (data['stack'] && !(typeof data['stack'] === 'string' || data['stack'] instanceof String)) {
            throw new Error("Expected the field `stack` to be a primitive type in the JSON string but got " + data['stack']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }
        if (data['buildpacks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['buildpacks'])) {
                throw new Error("Expected the field `buildpacks` to be an array in the JSON data but got " + data['buildpacks']);
            }
            // validate the optional field `buildpacks` (array)
            for (const item of data['buildpacks']) {
                AppBuildpacksInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['pipeline_stage'] && !(typeof data['pipeline_stage'] === 'string' || data['pipeline_stage'] instanceof String)) {
            throw new Error("Expected the field `pipeline_stage` to be a primitive type in the JSON string but got " + data['pipeline_stage']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }
        // ensure the json data is a string
        if (data['deleted_at'] && !(typeof data['deleted_at'] === 'string' || data['deleted_at'] instanceof String)) {
            throw new Error("Expected the field `deleted_at` to be a primitive type in the JSON string but got " + data['deleted_at']);
        }

        return true;
    }


}

App.RequiredProperties = ["id", "name", "team", "stack", "region"];

/**
 * @member {String} id
 */
App.prototype['id'] = undefined;

/**
 * @member {String} name
 */
App.prototype['name'] = undefined;

/**
 * @member {module:model/AppTeam} team
 */
App.prototype['team'] = undefined;

/**
 * @member {module:model/AppPipeline} pipeline
 */
App.prototype['pipeline'] = undefined;

/**
 * @member {String} dns_refreshed_at
 */
App.prototype['dns_refreshed_at'] = undefined;

/**
 * @member {Number} builds_count
 */
App.prototype['builds_count'] = undefined;

/**
 * @member {Number} deployments_count
 */
App.prototype['deployments_count'] = undefined;

/**
 * @member {Number} slugs_count
 */
App.prototype['slugs_count'] = undefined;

/**
 * @member {String} current_build_id
 */
App.prototype['current_build_id'] = undefined;

/**
 * @member {String} current_image_id
 */
App.prototype['current_image_id'] = undefined;

/**
 * @member {String} current_deployment_id
 */
App.prototype['current_deployment_id'] = undefined;

/**
 * @member {Object.<String, module:model/AppFormationValue>} formation
 */
App.prototype['formation'] = undefined;

/**
 * @member {String} stack
 */
App.prototype['stack'] = undefined;

/**
 * @member {String} region
 */
App.prototype['region'] = undefined;

/**
 * @member {Array.<module:model/AppBuildpacksInner>} buildpacks
 */
App.prototype['buildpacks'] = undefined;

/**
 * @member {String} description
 */
App.prototype['description'] = undefined;

/**
 * @member {String} pipeline_stage
 */
App.prototype['pipeline_stage'] = undefined;

/**
 * @member {Boolean} policy_allow_websockets
 */
App.prototype['policy_allow_websockets'] = undefined;

/**
 * @member {Number} policy_response_timeout
 */
App.prototype['policy_response_timeout'] = undefined;

/**
 * @member {Number} policy_max_connections
 */
App.prototype['policy_max_connections'] = undefined;

/**
 * @member {Number} policy_erosion_resistance_seconds
 */
App.prototype['policy_erosion_resistance_seconds'] = undefined;

/**
 * @member {Boolean} policy_share_process_namespace
 */
App.prototype['policy_share_process_namespace'] = undefined;

/**
 * @member {Boolean} policy_temporary_self_signed
 */
App.prototype['policy_temporary_self_signed'] = undefined;

/**
 * @member {String} created_at
 */
App.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
App.prototype['updated_at'] = undefined;

/**
 * @member {String} deleted_at
 */
App.prototype['deleted_at'] = undefined;






export default App;

