/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppFormationValue model module.
 * @module model/AppFormationValue
 * @version v1
 */
class AppFormationValue {
    /**
     * Constructs a new <code>AppFormationValue</code>.
     * Dyno formation
     * @alias module:model/AppFormationValue
     */
    constructor() { 
        
        AppFormationValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppFormationValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppFormationValue} obj Optional instance to populate.
     * @return {module:model/AppFormationValue} The populated <code>AppFormationValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppFormationValue();

            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'String');
            }
            if (data.hasOwnProperty('display')) {
                obj['display'] = ApiClient.convertToType(data['display'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppFormationValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppFormationValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['size'] && !(typeof data['size'] === 'string' || data['size'] instanceof String)) {
            throw new Error("Expected the field `size` to be a primitive type in the JSON string but got " + data['size']);
        }
        // ensure the json data is a string
        if (data['display'] && !(typeof data['display'] === 'string' || data['display'] instanceof String)) {
            throw new Error("Expected the field `display` to be a primitive type in the JSON string but got " + data['display']);
        }

        return true;
    }


}



/**
 * @member {String} size
 */
AppFormationValue.prototype['size'] = undefined;

/**
 * @member {String} display
 */
AppFormationValue.prototype['display'] = undefined;

/**
 * @member {Number} quantity
 */
AppFormationValue.prototype['quantity'] = undefined;






export default AppFormationValue;

