/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuildIoApiV1);
  }
}(this, function(expect, BuildIoApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuildIoApiV1.CreateNamespaceRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateNamespaceRequest', function() {
    it('should create an instance of CreateNamespaceRequest', function() {
      // uncomment below and update the code to test CreateNamespaceRequest
      //var instance = new BuildIoApiV1.CreateNamespaceRequest();
      //expect(instance).to.be.a(BuildIoApiV1.CreateNamespaceRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new BuildIoApiV1.CreateNamespaceRequest();
      //expect(instance).to.be();
    });

    it('should have the property teamId (base name: "team_id")', function() {
      // uncomment below and update the code to test the property teamId
      //var instance = new BuildIoApiV1.CreateNamespaceRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new BuildIoApiV1.CreateNamespaceRequest();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new BuildIoApiV1.CreateNamespaceRequest();
      //expect(instance).to.be();
    });

  });

}));
