/**
 * Build.io API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BuildIoApiV1);
  }
}(this, function(expect, BuildIoApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BuildIoApiV1.Process();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Process', function() {
    it('should create an instance of Process', function() {
      // uncomment below and update the code to test Process
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be.a(BuildIoApiV1.Process);
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "started_at")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be();
    });

    it('should have the property restarts (base name: "restarts")', function() {
      // uncomment below and update the code to test the property restarts
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be();
    });

    it('should have the property restartedAt (base name: "restarted_at")', function() {
      // uncomment below and update the code to test the property restartedAt
      //var instance = new BuildIoApiV1.Process();
      //expect(instance).to.be();
    });

  });

}));
